SLC/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('tasks/', include('tasks.urls')),
]

tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'

urlpatterns = [
    path('', views.index, name='index'),
    path('criado_categoria', views.criar_categoria, name='criar_categoria'),
    path('<int:categoria_id>/criado_produto', views.criar_produto, name='criar_produto'),
    path('<int:produto_id>/deletado_produto',views.deletar_produto, name='deletar_produto'),
    path('<int:categoria_id>/deletado_categoria', views.deletar_categoria, name='deletar_categoria')
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login.html', views.login, name='login'),
    path('cadastrar.html', views.cadastrar, name='cadastro'),
    path('logout', views.logout, name='logout'),
]

tasks/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=64)
    quantidade = models.IntegerField(default=1)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=64)
    produtos = models.ManyToManyField(Product, blank=True, related_name="categorias")

    def __str__(self):
        return self.name

tasks/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .models import Product,Category
from django.http import HttpResponseRedirect
from django.urls import reverse


@login_required(login_url="users:login")
def index(request):
    return render(request, 'tasks/index.html', {
        'categorias': Category.objects.all(),
        })


def criar_categoria(request):
    if request.method == 'POST':
        nome_categoria = request.POST['categoria']
        categoria = Category.objects.create(name=nome_categoria)
        categoria.save()

        return HttpResponseRedirect(reverse("tasks:index"))

def criar_produto(request, categoria_id):
    if request.method == 'POST':
        nome_produto = request.POST['produto']
        quantidade = request.POST['quantidade']
        produto = Product.objects.create(name=nome_produto, quantidade=quantidade)
        produto.save()

        categoria = Category.objects.get(id=categoria_id)

        produto.categorias.add(categoria)

        return HttpResponseRedirect(reverse("tasks:index"))

def deletar_produto(request, produto_id):
    if request.method == 'POST':
        produto = Product.objects.get(id=produto_id)
        produto.delete()

        return HttpResponseRedirect(reverse("tasks:index"))
    
def deletar_categoria(request, categoria_id):
    if request.method == 'POST':
        categoria = Category.objects.get(id=categoria_id)

        for produto_name in categoria.produtos.all():
            produto = Product.objects.get(name=produto_name)
            produto.delete()

        categoria.delete()

        return HttpResponseRedirect(reverse("tasks:index"))

users/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth import login as login_django
from django.contrib.auth import logout as logout_django
from django.http import HttpResponseRedirect
from django.urls import reverse

# Função para cadastrar usuario:
def cadastrar(request):
    if request.method == 'POST':
        # Pegando os valores dados pelo html "cadastrar.html":
        username = request.POST['username']
        email = request.POST['email']
        senha = request.POST['senha']
        
        # Verificando se o usuario já existe:
        user = User.objects.filter(username=username).first()
        
        if user:
            return HttpResponse('Já existe um usuário com esse nome')
        
        # Criando um usuario:
        user = User.objects.create_user(username=username, email=email, password=senha)
        user.save()

        return render(request, 'users/login.html', {'message': 'Usuário cadastrado com sucesso'})

    return render(request, 'users/cadastrar.html')

# Função para efetuar o login do usuario:
def login(request):
    if request.method == 'POST':
        # Pegando os valores dados pelo html "login.html":
        username = request.POST['username']
        senha = request.POST['senha']

        # Verificando o usuario:
        user = authenticate(username=username, password=senha)

        if user:
            login_django(request, user) # Logando o usuario
            return HttpResponseRedirect(reverse('tasks:index'))

        else:
            return render(request, 'users/login.html', {'message': 'Nome ou senha invalidos!'})
    return render(request, 'users/login.html')

# Função para deslogar o usuario:
def logout(request):
    logout_django(request) # Deslogando o usuario
    return render(request, 'users/login.html', {
        'message': 'Você se desconectou'
    })

tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
    <style>
        input[type="submit" i] {
            cursor: pointer;
        }
    </style>
    <h1>
        Bem vindo<br>
        Faça sua lista de compras:
    </h1>

    <p>Se você desejar deslogar:</p>
    <a href="{% url 'users:logout' %}">Log Out</a>

    <h2>Crie uma categoria</h2>
    <form action="{% url 'tasks:criar_categoria' %}" method="post">
        {% csrf_token %}
        <input type="text" placeholder="Digite a categoria" name="categoria">
        <br><br>
        <input type="submit" value="Criar">
    </form>

    <br>

    <h2>Suas categorias:</h2>
    <hr>
    {% for categoria in categorias %}
        <div style="display: flex; align-items: center;">
            <h3>{{ categoria }}</h3>
            <div style="margin-left: 12px;">
                <form action="{% url 'tasks:deletar_categoria' categoria.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Deletar">
                </form>
            </div>
        </div>
        <h4>Criar produto</h4>
        <form action="{% url 'tasks:criar_produto' categoria.id %}" method="post">
            {% csrf_token %}
            <input type="text" placeholder="Digite o produto" name="produto">
            <input type="number" placeholder="Digite a quantidade" name="quantidade">
            <br><br>
            <input type="submit" value="Criar">
        </form>
        <br>

        <h3>Produtos:</h3>
        <ul>
            {% for produto in categoria.produtos.all %}
                <li>
                    <div style="display: flex; align-items: center;">
                        <p>{{ produto }} ({{ produto.quantidade }})</p>
                        <div style="margin-left: 12px;">
                            <form action="{% url 'tasks:deletar_produto' produto.id %}" method="post">
                                {% csrf_token %}
                                <input type="submit" value="Deletar">
                            </form>
                        </div>
                    </div>
                </li>
            {% endfor %}      
        </ul>

        <br><hr>
    {% endfor %}
{% endblock %}

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasks</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

users/templates/users/cadastrar.html
{% extends "users/layout.html" %}

{% block body %}
    <h1>Faça o cadastro</h1>
    <form action="{% url 'users:cadastro' %}" method="post">
        {% csrf_token %}
        <input type="text" placeholder="Username..." name="username">
        <br><br>
        <input type="email" placeholder="Email..." name="email">
        <br><br>
        <input type="password" placeholder="Senha..." name="senha">
        <br><br>
        <input type="submit" value="Cadastrar">
        <br><br>
        <a href="{% url 'users:login' %}">Login</a>
    </form>
{% endblock %}

users/templates/users/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Users</title>
        <link rel="stylesheet" href="{% static 'users/styles.css' %}">
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

users/templates/users/login.html
{% extends "users/layout.html" %}

{% block body %}
    {% if message %}
        <div style="display: flex; justify-content: center; align-items: center; flex-direction: column;">
            {{ message }}
        </div>
    {% endif %}
    <br><br>
    <h1>Faça o login</h1>
    <form action="{% url 'users:login' %}" method="POST">
        {% csrf_token %}
        <input type="text" placeholder="Username..." name="username">
        <br><br>
        <input type="password" placeholder="Senha..." name="senha">
        <br><br>
        <input type="submit" value="Logar">
        <br>
        <br>
        <a href="cadastrar.html">Cadastrar</a>
    </form>
{% endblock %}